[project]
name = "fastapi-educ"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[all]>=0.115.6",
    "uvicorn>=0.34.0",
]
