[project]
name = "fastapi-educ"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "alembic>=1.14.0",
    "asyncpg>=0.30.0",
    "fastapi[all]>=0.115.6",
    "pydantic-settings>=2.7.1",
    "sqlalchemy>=2.0.37",
    "uvicorn>=0.34.0",
]
