line-length = 80

[lint.per-file-ignores]
"*/versions/*.py" = ["E501"]
"env.py" = ["F401", "I001"]
  # init modules can contain the local imports, logic, unused imports
"__init__.py" = ["F401"]


[lint]
preview = true
select = ["E", "F", "I", "C90"]
